// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChYPaVkxEK2KCUZwnxrHXe2SJ2B4XL18E',
    appId: '1:675024117476:web:c93fd5c7df6c19a430d6f1',
    messagingSenderId: '675024117476',
    projectId: 'hbcshuttlers',
    authDomain: 'hbcshuttlers.firebaseapp.com',
    databaseURL: 'https://hbcshuttlers.firebaseio.com',
    storageBucket: 'hbcshuttlers.appspot.com',
    measurementId: 'G-JEYFKFPNK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvY2N9LRp3lyDYFa99L4OVGJUWJB0uJGM',
    appId: '1:675024117476:android:23726d66a75f352630d6f1',
    messagingSenderId: '675024117476',
    projectId: 'hbcshuttlers',
    databaseURL: 'https://hbcshuttlers.firebaseio.com',
    storageBucket: 'hbcshuttlers.appspot.com',
  );
}
